# Generated by Django 5.2.9 on 2026-02-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sale_expenditure'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='capacity',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
